import { FiEdit, FiLogIn, FiShare2 } from 'react-icons/fi'

import Container from "../components/Container"
import Footer from "../components/Footer"
import Head from 'next/head'
import Header from "../components/Header"
import Info from "../components/Info"
import Partners from "../components/Partners"

export default function Home () {
  return (
    <div>
      <Head>
        <title>Every Kid Rox | Knowledge base for parents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <div className="relative">
          <div className="text-center z-20 text-slate-800 md:my-8 my-12">
            <h1 className="mb-2">Wonderfully Unique</h1>
            <p>Helping parents give their children the best care</p>
          </div>
        </div>
      </Container>
      <Container>
        <Partners />
      </Container>
      <Info />
      <Container>
        <div className="text-center mb-16">
          <h2 className="mb-2">Simplifying the tedious</h2>
          <p>To give you more time for the important things</p>
        </div>
        <div className="flex flex-col md:flex-row gap-12">
          <div className="basis-1/3 space-y-3">
            <div className="w-12 h-12 bg-cyan-500 shadow-cyan-500/40 shadow-lg rounded-xl flex justify-center items-center">
              <FiLogIn size={20} className="text-white" />
            </div>
            <h4 className="font-sans font-medium text-cyan-600">Sign up</h4>
            <h3 className="text-xl">Signing up with an account only takes seconds</h3>
            <p>Dolor anim id anim consequat. Consequat adipisicing reprehenderit elit esse ex proident consectetur ea occaecat. Nostrud laborum quis deserunt ut minim consectetur voluptate nostrud aliquip et. </p>
          </div>
          <div className="basis-1/3 space-y-3">
            <div className="w-12 h-12 bg-sky-600 shadow-sky-500/40 shadow-lg rounded-xl flex justify-center items-center">
              <FiEdit size={20} className="text-white" />
            </div>
            <h4 className="font-sans font-medium text-sky-600">Fill</h4>
            <h3 className="text-xl">Enter your documents <i>ONCE</i></h3>
            <p>Dolor anim id anim consequat. Consequat adipisicing reprehenderit elit esse ex proident consectetur ea occaecat. Nostrud laborum quis deserunt ut minim consectetur voluptate nostrud aliquip et. </p>
          </div>
          <div className="basis-1/3 space-y-3">
            <div className="w-12 h-12 bg-blue-700 shadow-blue-500/40 shadow-lg rounded-xl flex justify-center items-center">
              <FiShare2 size={20} className="text-white" />
            </div>
            <h4 className="font-sans font-medium text-blue-600">Share</h4>
            <h3 className="text-xl">Easily share your documents with one click</h3>
            <p>Dolor anim id anim consequat. Consequat adipisicing reprehenderit elit esse ex proident consectetur ea occaecat. Nostrud laborum quis deserunt ut minim consectetur voluptate nostrud aliquip et. </p>
          </div>
        </div>
      </Container>
      <div className="bg-[url('/images/banner.jpg')] bg-center bg-cover py-40 relative px-8">
        <div className="bg-[url('/images/bg-blur.jpg')] bg-center bg-cover pt-40 absolute inset-0 z-10 opacity-90"></div>
        <div className="max-w-6xl mx-auto z-20 relative">
          <div className="max-w-lg text-white text-center mx-auto z-20">
            <h2 className="capitalize mb-4">Get start today</h2>
            <p className="text-white mb-8">Excepteur culpa dolor cupidatat eiusmod elit. Ad velit in elit quis dolore dolore dolore ullamco dolor ex.</p>
            <button className="px-4 py-2 text-blue-600 rounded-lg shadow-lg shadow-white/30 bg-white capitalize">Let's get going</button>
          </div>
        </div>
      </div>
      <div className="max-w-6xl mx-auto">
        <Footer />
      </div>
    </div>
  )
}
